---
language: python
python: "3.9"
sudo: required

env:
  - PIPENV_IGNORE_VIRTUALENVS=1
  - MOLECULE_DISTRO=debian:buster-slim
  - MOLECULE_DISTRO=debian:bullseye-slim

services:
  - docker

install:
  - pip install pipenv==2018.11.26
  - pipenv install -r test-requirements.txt
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
