---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: opengrok-container-test
    image: ${MOLECULE_DISTRO:-idealista/jdk:8u382-bullseye-temurin-jdk}
    privileged: false
    command: '/lib/systemd/systemd'
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'

    groups:
      - opengrok

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
  log: True
scenario:
  name: default
verifier:
  name: ansible
